all: test.elf

CFLAGS := -Os -DONLY_MSPACES -DNO_MALLOC_STATS -DNO_MALLINFO -DHAVE_MMAP=0 -DNO_MSPACES_FOOTPRINT -DNO_MSPACES_REALLOC -DNO_MSPACES_IALLOC -DNO_MSPACES_MEMALIGN -DNO_MSPACES_BULK_FREE -DNO_MSPACES_MALLOPT

test.elf:test.o malloc.o
	gcc ${CFLAGS} $^ -o $@

clean:
	-rm test.o malloc.o test.elf
